### ISSUE TITLE
How to get API? 

### ISSUE THREAD

**Issue by psychobmw98** [magneum/Vlkyre#12]
Hello, does this system support self host?

**Comment by Kryknz** [comment]
Yes It Does!

**Comment by psychobmw98** [comment]
![Screenshot_2022-07-02-16-07-17-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/36082995/177004196-20208c45-9723-495e-8ce0-6839b9063c43.jpg)


It shows Heroku require, what can I put there?
