### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by scarletStrange** [magneum/Vlkyre#24]
08:58:52 debug: 🐲: New Login.
08:58:52 error: ❌: Restart Required, Restarting...
08:58:52 info: 🐲: Connected with Mongoose.
08:58:52 error: listen EADDRINUSE: address already in use :::5000
08:58:52 info: 🐲: Connecting to WhatsApp...▶
08:58:58 info: 🐲: Login successful! ▶
08:58:58 debug: 🐲: Received Pending Notifications.
08:59:12 error: Connection Closed
08:59:12 error: forbidden
08:59:12 error: forbidden
08:59:13 error: forbidden
08:59:13 error: forbidden
08:59:13 error: forbidden
08:59:13 error: forbidden
08:59:23 error: forbidden
08:59:23 error: forbidden
08:59:23 error: forbidden
08:59:33 error: fatal: not a git repository (or any of the parent directories): .git

08:59:52 error: Connection Closed
09:00:13 error: fatal: not a git repository (or any of the parent directories): .git

09:00:32 error: Connection Closed
09:00:33 error: forbidden
09:00:37 error: forbidden
09:00:40 error: forbidden
09:00:53 error: fatal: not a git repository (or any of the parent directories): .git

09:01:12 error: Connection Closed
09:01:33 error: fatal: not a git repository (or any of the parent directories): .git

09:01:52 error: Connection Closed

what's the issue?? successful login. but forbidden.

**Comment by magneum** [comment]
Bot in version 0.1.2... let it reach version 1.0.0 then you can try
deployment

**Comment by scarletStrange** [comment]
So i cannot use the bot at this moment?

**Comment by magneum** [comment]
Dear Shovit Dutta,

We are writing to inform you about the upcoming offline examinations for
the Data Science, Artificial Intelligence, and Machine Learning using
Python course at Ardent Computech. Here are the details:

- Course: Data Science, Artificial Intelligence, and Machine Learning using
Python
- Registration Number: 202000147
- Examination Dates: 9th July 2023 to 16th July 2023 (between these two
Sundays)
- Examination Venue: Ardent Computech, Module 132, SDF Building, Salt Lake,
Sector V, Kolkata - 700091

Please make sure to arrive at Ardent Computech on time and bring your
registration number for verification.

As a Hybrid Student, we appreciate your dedication to pursuing your
education. Whether you are attending classes in person or remotely, we
assure you that we are committed to providing a conducive environment for
your success.

For any assistance or queries, you can visit our website at
https://www.ardentcollaborations.com or contact our help desk at:
- Contact No: 18008904233 / 9674735471 / 9674735470 / 8337066991
- Email: ***@***.***

Prepare for the exams by reviewing the course materials provided by Ardent
Computech. Effective time management and solving previous question papers
and sample tests can enhance your performance.

We appreciate your dedication to your education and trust in Ardent
Computech. We are here to support you throughout your educational journey.

If you need further information or have any concerns, feel free to reach
out to us. We are dedicated to your success.

Best regards,

Shovit Dutta
Hybrid Student
Ardent Computech
